# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'myUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1526, 864)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: (12,34,56)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setEnabled(True)
        self.frame.setGeometry(QtCore.QRect(0, 260, 231, 241))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: \"#63D3FF\";\n"
"    border: 2px solid black;\n"
"    border-radius: 2px;\n"
"}\n"
"QListWidget{\n"
"    border: none;\n"
"background-color: \"#20C0FF\"\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: \"#63D3FF\";\n"
"    border: 2px solid white;\n"
"    border-radius: 2px;\n"
"    color: white;\n"
"    font-family: Monospace \"Courier New\";\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font-size: 15px;\n"
"    background-color: \"#20C0FF\";\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: gray;\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.addButton = QtWidgets.QPushButton(self.frame)
        self.addButton.setGeometry(QtCore.QRect(10, 186, 71, 51))
        self.addButton.setStyleSheet("")
        self.addButton.setObjectName("addButton")
        self.exitButton = QtWidgets.QPushButton(self.frame)
        self.exitButton.setGeometry(QtCore.QRect(150, 186, 71, 51))
        self.exitButton.setStyleSheet("")
        self.exitButton.setObjectName("exitButton")
        self.removeButton = QtWidgets.QPushButton(self.frame)
        self.removeButton.setEnabled(False)
        self.removeButton.setGeometry(QtCore.QRect(80, 186, 71, 51))
        self.removeButton.setStyleSheet("")
        self.removeButton.setObjectName("removeButton")
        self.listWidget = QtWidgets.QListWidget(self.frame)
        self.listWidget.setGeometry(QtCore.QRect(10, 10, 211, 171))
        self.listWidget.setStyleSheet("QListWidget{\n"
"    color: white;\n"
"    font-family: Lucida\n"
"    \n"
"}\n"
"\n"
"\n"
"QScrollBar{\n"
"    background-color: \"#63D3FF\";\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"QScrollBar::handle{\n"
"    border: 1px solid \"#63DFFFF\";\n"
"    background-color: \"#20C0FF\"\n"
"}\n"
"QScrollBar::handle::pressed{\n"
"    border: 1.5px solid black;\n"
"    \n"
"}")
        self.listWidget.setObjectName("listWidget")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setEnabled(True)
        self.frame_2.setGeometry(QtCore.QRect(0, 510, 241, 261))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: \"#63D3FF\";\n"
"    border: 2px solid black;\n"
"    border-radius: 2px;\n"
"}\n"
"/* Make code for the input boxes and the labels\n"
" */\n"
"QLabel{\n"
"    color: white;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLineEdit{\n"
"background-color: \"#20C0FF\";\n"
"border: none;\n"
"}\n"
"\n"
"QTextEdit{\n"
"    border: none;\n"
"    background-color: \"#20C0FF\";\n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: \"#63D3FF\";\n"
"    border: 2px solid white;\n"
"    border-radius: 2px;\n"
"    color: white;\n"
"    font-family: Monospace \"Courier New\";\n"
"    font-weight: bold;\n"
"}\n"
"QPushButton:hover{\n"
"    font-size: 15px;\n"
"    background-color: \"#20C0FF\";\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"background-color: gray;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 10, 221, 21))
        self.label.setStyleSheet("border: none;")
        self.label.setObjectName("label")
        self.titleInput = QtWidgets.QLineEdit(self.frame_2)
        self.titleInput.setGeometry(QtCore.QRect(10, 60, 211, 22))
        self.titleInput.setObjectName("titleInput")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(20, 38, 151, 21))
        self.label_2.setStyleSheet("border: none;")
        self.label_2.setObjectName("label_2")
        self.infoInput = QtWidgets.QTextEdit(self.frame_2)
        self.infoInput.setGeometry(QtCore.QRect(10, 110, 211, 87))
        self.infoInput.setObjectName("infoInput")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(20, 89, 151, 21))
        self.label_3.setStyleSheet("border: none;")
        self.label_3.setObjectName("label_3")
        self.aatdDoneButton = QtWidgets.QPushButton(self.frame_2)
        self.aatdDoneButton.setGeometry(QtCore.QRect(10, 220, 93, 28))
        self.aatdDoneButton.setObjectName("aatdDoneButton")
        self.aatdCancelButton = QtWidgets.QPushButton(self.frame_2)
        self.aatdCancelButton.setGeometry(QtCore.QRect(130, 220, 93, 28))
        self.aatdCancelButton.setStyleSheet("")
        self.aatdCancelButton.setObjectName("aatdCancelButton")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 510, 241, 261))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: \"#20C0FF\"\n"
"    border: 2px solid black;\n"
"    border-radius: 2px;\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 221, 241))
        self.textBrowser.setStyleSheet("QTextBrowser{\n"
"    background-color: \"#63D3FF\";\n"
"    border: none;\n"
"    color: black;\n"
"}\n"
"QScrollBar{\n"
"    background-color: \"#63D3FF\";\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"      border: none;\n"
"      background: none;\n"
"}\n"
"QScrollBar::handle{\n"
"    border: 1px solid \"#63DFFFF\";\n"
"    background-color: \"#20C0FF\"\n"
"}\n"
"QScrollBar::handle::pressed{\n"
"    border: 1.5px solid black;\n"
"}")
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Copy Paste into UI
        MainWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint | QtCore.Qt.WindowStaysOnTopHint)
        MainWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        MainWindow.showMaximized()

        self.to_do_list = []

        self.exitButton.clicked.connect(lambda: exit())

        def setAATDFrame(value):
                self.frame_2.setHidden(value)

        def addToDo(flag):
                if (flag != "cancel"):
                        self.to_do_list.append({"TITLE": self.titleInput.text(), "INFO": self.infoInput.toPlainText()})
                        self.listWidget.addItem(" • " + self.titleInput.text())
                self.infoInput.clear()
                self.titleInput.setText("")
                setAATDFrame(True)


        setAATDFrame(True)
        self.frame_3.setHidden(True)
        self.addButton.clicked.connect(lambda: setAATDFrame(False))
        self.aatdDoneButton.clicked.connect(lambda: addToDo(""))
        self.aatdCancelButton.clicked.connect(lambda: addToDo("cancel"))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.addButton.setText(_translate("MainWindow", "ADD"))
        self.exitButton.setText(_translate("MainWindow", "EXIT"))
        self.removeButton.setText(_translate("MainWindow", "REMOVE"))
        self.label.setText(_translate("MainWindow", "ADD A TO-DO"))
        self.label_2.setText(_translate("MainWindow", "TITLE:"))
        self.label_3.setText(_translate("MainWindow", "INFO:"))
        self.aatdDoneButton.setText(_translate("MainWindow", "DONE"))
        self.aatdCancelButton.setText(_translate("MainWindow", "CANCEL"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
